#!/usr/bin/env bash
# Set up (or update) the whole system on a fresh Ubuntu cloud server.
#
#   bash deploy/cloud/setup.sh
#
# Written for an Oracle Cloud "Always Free" Ubuntu server (docs/DEPLOY-ORACLE.md)
# and safe to run again at any time: it keeps your settings, data and
# certificates, and rebuilds whatever changed. To update to the latest version:
#
#   git pull && bash deploy/cloud/setup.sh
#
# What it does, in order:
#   1. installs Docker if it is missing;
#   2. opens the web ports in the server's own firewall (Oracle's Ubuntu
#      images block everything but SSH by default);
#   3. works out this server's permanent web addresses from its public IP;
#   4. on first run, writes deploy/cloud/.env with freshly generated secrets;
#   5. builds and starts everything;
#   6. on first run, asks for your admin username and password;
#   7. prints the links to share.

set -euo pipefail

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m  ok\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m  !\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO"
ENV_FILE="deploy/cloud/.env"

[ "$(uname -s)" = "Linux" ] || die "run this on the Linux cloud server, not on your own computer."
command -v sudo >/dev/null || die "sudo is required."

# --- 1. Docker -----------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    say "Installing Docker (a few minutes, once)..."
    curl -fsSL https://get.docker.com | sudo sh
fi
# Through sudo for the rest of this run: a group added just now only applies
# to new logins.
DOCKER="sudo docker"
$DOCKER compose version >/dev/null 2>&1 || die "Docker Compose is missing; re-run after: curl -fsSL https://get.docker.com | sudo sh"
ok "Docker ready"

compose() {
    $DOCKER compose --env-file "$ENV_FILE" -f deploy/compose.yaml -f deploy/cloud/compose.yaml "$@"
}

# --- 2. The server's own firewall ------------------------------------------------
# Oracle's Ubuntu images ship iptables rules that reject everything except SSH,
# *in addition to* the cloud network's rules (docs/DEPLOY-ORACLE.md, step 4).
# Both must allow 80 and 443. This handles the server's half.
if command -v iptables >/dev/null 2>&1; then
    for port in 80 443; do
        sudo iptables -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null \
            || sudo iptables -I INPUT 1 -p tcp --dport "$port" -j ACCEPT
    done
    sudo iptables -C INPUT -p udp --dport 443 -j ACCEPT 2>/dev/null \
        || sudo iptables -I INPUT 1 -p udp --dport 443 -j ACCEPT
    if command -v netfilter-persistent >/dev/null 2>&1; then
        sudo netfilter-persistent save >/dev/null 2>&1 || true
    fi
    ok "Web ports open in the server firewall"
fi

# --- 3. Permanent addresses ------------------------------------------------------
# sslip.io turns an IP address into a web name (1.2.3.4 -> 1.2.3.4.sslip.io)
# for free, with no account, so certificates can be issued without buying a
# domain. Set PUBLIC_HOST to use a domain of your own instead.
PUBLIC_IP="${PUBLIC_IP:-$(curl -fsS https://checkip.amazonaws.com | tr -d '[:space:]')}"
[ -n "$PUBLIC_IP" ] || die "could not work out this server's public IP; set PUBLIC_IP=... and re-run."
PUBLIC_HOST="${PUBLIC_HOST:-${PUBLIC_IP}.sslip.io}"
APP_HOST="app.${PUBLIC_HOST}"
API_HOST="api.${PUBLIC_HOST}"

# --- 4. Settings and secrets -----------------------------------------------------
secret() { openssl rand -hex 32; }
if [ ! -f "$ENV_FILE" ]; then
    say "Writing $ENV_FILE with new secrets (kept for every later run)..."
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by deploy/cloud/setup.sh. Contains secrets: never share or commit.
APP_HOST=${APP_HOST}
API_HOST=${API_HOST}
POSTGRES_PASSWORD=$(secret)
MINIO_ROOT_USER=orchestrator
MINIO_ROOT_PASSWORD=$(secret)
JWT_SIGNING_KEY=$(secret)
ADMIN_API_KEY=$(secret)
# The trainer peers pull and run; published on Docker Hub.
TRAINER_IMAGE=abhisheks1290/gpu-orchestrator-trainer:latest
SCHEDULER_STRATEGY=adaptive
# Anyone with the dashboard link can create an account. Set to false to
# create accounts yourself on the People page instead.
ALLOW_REGISTRATION=true
EOF
    ok "Settings written"
else
    # The server's IP can change if it was not reserved; keep the names in
    # step with it, and leave every other setting alone.
    sed -i "s|^APP_HOST=.*|APP_HOST=${APP_HOST}|; s|^API_HOST=.*|API_HOST=${API_HOST}|" "$ENV_FILE"
    ok "Keeping existing settings in $ENV_FILE"
fi

# --- 5. Build and start -----------------------------------------------------------
say "Building and starting (the first time takes 5-10 minutes)..."
compose up -d --build --remove-orphans

say "Waiting for the orchestrator to be ready..."
for _ in $(seq 1 90); do
    if compose exec -T orchestrator curl -fsS http://localhost:8000/health >/dev/null 2>&1; then
        break
    fi
    sleep 2
done
compose exec -T orchestrator curl -fsS http://localhost:8000/health >/dev/null 2>&1 \
    || die "the orchestrator did not start. See: sudo docker compose --env-file $ENV_FILE -f deploy/compose.yaml -f deploy/cloud/compose.yaml logs orchestrator"
ok "Orchestrator running"

# --- 6. The first admin account ----------------------------------------------------
admins="$(compose exec -T postgres psql -U orchestrator -d orchestrator -tAc \
    "select count(*) from users where role = 'ADMIN' and disabled_at is null" 2>/dev/null | tr -d '[:space:]')"
if [ "${admins:-0}" = "0" ]; then
    echo
    say "Create your admin account (you sign in with this)."
    while :; do
        read -rp "    Username (letters, numbers, . _ -): " admin_user
        [ -n "$admin_user" ] && break
    done
    while :; do
        read -rsp "    Password (at least 12 characters): " p1; echo
        read -rsp "    Type it again: " p2; echo
        if [ "$p1" = "$p2" ] && [ "${#p1}" -ge 12 ]; then break; fi
        warn "Those didn't match, or were shorter than 12 characters. Try again."
    done
    # By environment variable, never as an argument (scripts/create_user.py).
    compose exec -T -e ORCH_USER_PASSWORD="$p1" orchestrator \
        python -m scripts.create_user --username "$admin_user" --role ADMIN --no-prompt
    unset p1 p2
    ok "Admin account $admin_user created"
fi

# --- 7. Done ---------------------------------------------------------------------
say "Checking the website is reachable over HTTPS (certificates can take a minute)..."
reachable=no
for _ in $(seq 1 30); do
    if curl -fsS -o /dev/null "https://${APP_HOST}/"; then reachable=yes; break; fi
    sleep 4
done

echo
echo "  ====================================================================="
echo "   Website (send this to everyone):   https://${APP_HOST}"
echo "   Machines join through:             https://${API_HOST}"
echo "  ====================================================================="
echo "   These addresses are permanent. Sign in on the website, then use"
echo "   Machines -> Add a node to get the join command for each computer."
echo
if [ "$reachable" = "no" ]; then
    warn "The website isn't reachable from the internet yet. The usual cause is"
    warn "the cloud network's firewall: open ports 80 and 443 there"
    warn "(docs/DEPLOY-ORACLE.md, step 4), wait a minute, and run this again."
fi
