/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report liveness plus a real database connectivity probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Enrollment Token Endpoint
         * @description Mint a single-use enrollment token. Returns the raw token exactly once.
         */
        post: operations["create_enrollment_token_endpoint_auth_enrollment_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Challenge
         * @description Issue a single-use nonce for the given node to sign.
         */
        post: operations["issue_challenge_auth_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Verify a signed nonce and mint a new JWT.
         *
         *     The nonce is consumed atomically first (single-use); then the Ed25519
         *     signature over the nonce bytes is verified against the node's registered
         *     public key. Any failure is a flat 401.
         */
        post: operations["refresh_token_auth_token_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Enroll a node: consume the token, persist the node, return a first JWT.
         */
        post: operations["register_nodes_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heartbeat
         * @description Record a heartbeat for the authenticated, self-scoped node.
         */
        post: operations["heartbeat_nodes__node_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nodes Endpoint
         * @description List every enrolled node with its latest telemetry sample.
         *
         *     # TODO(M8): read-side auth — unauthenticated for dev.
         */
        get: operations["list_nodes_endpoint_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Endpoint
         * @description Return one node's current state plus its recent telemetry samples.
         *
         *     ``samples`` defaults to ``settings.node_detail_default_samples`` and is
         *     capped at ``settings.node_detail_max_samples`` regardless of what is
         *     requested.
         *
         *     # TODO(M8): read-side auth — unauthenticated for dev.
         */
        get: operations["get_node_endpoint_nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs Endpoint
         * @description List every job, newest first.
         *
         *     # TODO(M8): user auth — unauthenticated for dev.
         */
        get: operations["list_jobs_endpoint_jobs_get"];
        put?: never;
        /**
         * Submit Job
         * @description Validate the spec, enqueue the job (QUEUED), and trigger a scheduler pass.
         *
         *     The effective scheduler is the request's ``scheduler_name`` or the server
         *     default; either way it must be a registered strategy (``adaptive`` is not
         *     registered until M3, so it is rejected here).
         *
         *     # TODO(M8): user auth — unauthenticated for dev.
         */
        post: operations["submit_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Endpoint
         * @description One job with its full event timeline and leases.
         *
         *     # TODO(M8): user auth — unauthenticated for dev.
         */
        get: operations["get_job_endpoint_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/scheduling-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Scheduling Decisions
         * @description The adaptive scheduler's audit trail for this job (ADR-009).
         *
         *     One decision per scheduling pass that considered the job, newest first, each
         *     with the weights used and the per-candidate L/R/D/S breakdown that explains
         *     the pick. Empty for a job placed by a baseline scheduler (only ``adaptive``
         *     records decisions) or never scheduled. 404 only if the job itself is unknown.
         *
         *     # TODO(M8): user auth — unauthenticated for dev.
         */
        get: operations["get_job_scheduling_decisions_jobs__job_id__scheduling_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job Endpoint
         * @description Cancel a non-terminal job, releasing any ACTIVE lease.
         *
         *     # TODO(M8): user auth — unauthenticated for dev.
         */
        post: operations["cancel_job_endpoint_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/leases/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim Lease
         * @description Claim one job scheduled to this node, or return ``lease: null`` if none.
         */
        post: operations["claim_lease_nodes__node_id__leases_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases/{lease_id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew
         * @description Extend an ACTIVE lease's TTL (epoch-fenced).
         */
        post: operations["renew_leases__lease_id__renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases/{lease_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete
         * @description Finish a lease successfully (epoch-fenced); job → COMPLETED.
         */
        post: operations["complete_leases__lease_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases/{lease_id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fail
         * @description Finish a lease as failed (epoch-fenced); job → FAILED with a reason.
         */
        post: operations["fail_leases__lease_id__fail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChallengeRequest
         * @description Body of POST /auth/challenge.
         */
        ChallengeRequest: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
        };
        /**
         * ChallengeResponse
         * @description A fresh nonce for the agent to sign with its Ed25519 private key.
         */
        ChallengeResponse: {
            /** Nonce */
            nonce: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * ClaimResponse
         * @description Result of POST /nodes/{id}/leases/claim.
         *
         *     ``lease`` is the granted lease, or ``null`` when there was no work scheduled
         *     to this node right now (a clean empty-handed poll, not an error).
         */
        ClaimResponse: {
            lease: components["schemas"]["LeaseOut"] | null;
        };
        /**
         * EnrollmentTokenCreateRequest
         * @description Body of POST /auth/enrollment-tokens (admin-only).
         */
        EnrollmentTokenCreateRequest: {
            /** Created By */
            created_by: string;
            /** Ttl Seconds */
            ttl_seconds?: number | null;
        };
        /**
         * EnrollmentTokenCreateResponse
         * @description The raw token is returned here exactly once and never stored in the clear.
         */
        EnrollmentTokenCreateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Token */
            token: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * GpuInfo
         * @description One GPU's static inventory. Absent GPUs are represented by an empty list,
         *     never a fabricated entry.
         */
        GpuInfo: {
            /** Name */
            name: string;
            /** Vram Bytes */
            vram_bytes: number;
            /** Driver Version */
            driver_version: string;
        };
        /**
         * GpuTelemetry
         * @description Per-GPU live telemetry. ``temperature_c``/``power_w`` are optional because
         *     a given driver may not expose them; when unavailable they are ``null``.
         */
        GpuTelemetry: {
            /** Util Percent */
            util_percent: number;
            /** Mem Used Bytes */
            mem_used_bytes: number;
            /** Mem Total Bytes */
            mem_total_bytes: number;
            /** Temperature C */
            temperature_c?: number | null;
            /** Power W */
            power_w?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HardwareInventory
         * @description Truthful static hardware inventory for a node.
         */
        HardwareInventory: {
            /** Hostname */
            hostname: string;
            /** Os */
            os: string;
            /** Cpu Model */
            cpu_model: string;
            /** Cores */
            cores: number;
            /** Ram Bytes */
            ram_bytes: number;
            /** Gpus */
            gpus?: components["schemas"]["GpuInfo"][];
        };
        /**
         * HeartbeatRequest
         * @description Body of POST /nodes/{id}/heartbeat.
         *
         *     ``gpu`` is ``null`` when the agent has no GPU telemetry (e.g. NVML absent);
         *     ``rtt_ms`` is ``null`` until the agent has measured a round trip. Neither is
         *     ever filled in server-side.
         */
        HeartbeatRequest: {
            /** Cpu Percent */
            cpu_percent: number;
            /** Ram Used Bytes */
            ram_used_bytes: number;
            /** Ram Total Bytes */
            ram_total_bytes: number;
            /** Gpu */
            gpu?: components["schemas"]["GpuTelemetry"][] | null;
            /** Rtt Ms */
            rtt_ms?: number | null;
        };
        /**
         * HeartbeatResponse
         * @description Heartbeat acknowledgement.
         *
         *     ``server_time`` lets the agent measure the round trip client-side; the
         *     server never invents RTT. ``rtt_ewma_ms`` is the server's smoothed RTT and
         *     is ``null`` until at least one RTT has been measured.
         */
        HeartbeatResponse: {
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /**
             * Last Heartbeat At
             * Format: date-time
             */
            last_heartbeat_at: string;
            /** Status */
            status: string;
            /** Rtt Ewma Ms */
            rtt_ewma_ms: number | null;
        };
        /**
         * JobDetailResponse
         * @description Body of GET /jobs/{id}: the summary plus its full audit trail and leases.
         */
        JobDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Spec */
            spec: Record<string, never>;
            /** Scheduler Name */
            scheduler_name: string;
            /** State */
            state: string;
            /** Current Lease Epoch */
            current_lease_epoch: number;
            /** Scheduled Node Id */
            scheduled_node_id: string | null;
            /** Submitted By */
            submitted_by: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Failure Reason */
            failure_reason: string | null;
            /** Events */
            events: components["schemas"]["JobEventOut"][];
            /** Leases */
            leases: components["schemas"]["LeaseOut"][];
        };
        /**
         * JobEventOut
         * @description One recorded state transition for the job timeline.
         */
        JobEventOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** From State */
            from_state: string | null;
            /** To State */
            to_state: string;
            /** Detail */
            detail: Record<string, never>;
        };
        /**
         * JobListResponse
         * @description Body of GET /jobs.
         */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
        };
        /**
         * JobSpec
         * @description A training job's specification.
         */
        JobSpec: {
            /**
             * Dataset
             * @enum {string}
             */
            dataset: "cifar10" | "mnist";
            /** Model */
            model: string;
            /** Epochs */
            epochs: number;
            /** Batch Size */
            batch_size: number;
            /** Learning Rate */
            learning_rate: number;
            /** World Size */
            world_size: number;
            /** Min Gpu Mem Bytes */
            min_gpu_mem_bytes?: number | null;
        };
        /**
         * JobSubmitRequest
         * @description Body of POST /jobs.
         *
         *     ``scheduler_name`` is optional; when omitted the server's configured
         *     ``SCHEDULER_STRATEGY`` default is used. Whatever is chosen must be a
         *     registered scheduler (validated in the handler).
         */
        JobSubmitRequest: {
            spec: components["schemas"]["JobSpec"];
            /** Scheduler Name */
            scheduler_name?: string | null;
            /** Submitted By */
            submitted_by: string;
        };
        /**
         * JobSummary
         * @description A job's core fields for the list view.
         */
        JobSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Spec */
            spec: Record<string, never>;
            /** Scheduler Name */
            scheduler_name: string;
            /** State */
            state: string;
            /** Current Lease Epoch */
            current_lease_epoch: number;
            /** Scheduled Node Id */
            scheduled_node_id: string | null;
            /** Submitted By */
            submitted_by: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Failure Reason */
            failure_reason: string | null;
        };
        /**
         * LeaseEpochRequest
         * @description Body carrying just the fencing epoch (renew / complete).
         */
        LeaseEpochRequest: {
            /** Lease Epoch */
            lease_epoch: number;
        };
        /**
         * LeaseFailRequest
         * @description Body of POST /leases/{id}/fail: fencing epoch plus a real reason.
         */
        LeaseFailRequest: {
            /** Lease Epoch */
            lease_epoch: number;
            /** Reason */
            reason: string;
        };
        /**
         * LeaseOut
         * @description A lease row as returned to clients.
         */
        LeaseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Lease Epoch */
            lease_epoch: number;
            /** State */
            state: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Renewed At */
            renewed_at: string | null;
            /** Released At */
            released_at: string | null;
        };
        /**
         * NodeDetailResponse
         * @description Body of GET /nodes/{id}: the summary plus a capped, recent sample window.
         */
        NodeDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Heartbeat Stale */
            heartbeat_stale: boolean;
            hardware: components["schemas"]["HardwareInventory"];
            /** Lease Success Count */
            lease_success_count: number;
            /** Lease Failure Count */
            lease_failure_count: number;
            latest_telemetry: components["schemas"]["TelemetrySampleOut"] | null;
            /** Telemetry Samples */
            telemetry_samples: components["schemas"]["TelemetrySampleOut"][];
        };
        /**
         * NodeListResponse
         * @description Body of GET /nodes.
         */
        NodeListResponse: {
            /** Nodes */
            nodes: components["schemas"]["NodeSummary"][];
        };
        /**
         * NodeRegisterRequest
         * @description Body of POST /nodes/register.
         */
        NodeRegisterRequest: {
            /** Enrollment Token */
            enrollment_token: string;
            /** Public Key */
            public_key: string;
            hardware: components["schemas"]["HardwareInventory"];
            /** Agent Version */
            agent_version: string;
        };
        /**
         * NodeRegisterResponse
         * @description Result of a successful enrollment: identity plus a first access token.
         */
        NodeRegisterResponse: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Name */
            name: string;
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * NodeSummary
         * @description One node's current state for the fleet list view.
         *
         *     ``heartbeat_stale`` is computed at read time from ``last_heartbeat_at`` and
         *     the configured staleness window — it never mutates ``status``; declaring a
         *     node failed is the failure detector's job (ADR-004, M6).
         */
        NodeSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Heartbeat Stale */
            heartbeat_stale: boolean;
            hardware: components["schemas"]["HardwareInventory"];
            /** Lease Success Count */
            lease_success_count: number;
            /** Lease Failure Count */
            lease_failure_count: number;
            latest_telemetry: components["schemas"]["TelemetrySampleOut"] | null;
        };
        /**
         * SchedulingCandidateOut
         * @description One node considered in a decision, with its scores and raw inputs.
         */
        SchedulingCandidateOut: {
            /** Node Id */
            node_id: string | null;
            /** Node Name */
            node_name: string;
            /** L Score */
            l_score: number;
            /** R Score */
            r_score: number;
            /** D Score */
            d_score: number;
            /** S Score */
            s_score: number;
            /** Raw Util */
            raw_util: number | null;
            /** Raw Rtt Ewma Ms */
            raw_rtt_ewma_ms: number | null;
            /** Weighted Success */
            weighted_success: number;
            /** Weighted Failure */
            weighted_failure: number;
            /** Was Selected */
            was_selected: boolean;
        };
        /**
         * SchedulingDecisionListResponse
         * @description Body of GET /jobs/{id}/scheduling-decisions.
         */
        SchedulingDecisionListResponse: {
            /** Decisions */
            decisions: components["schemas"]["SchedulingDecisionOut"][];
        };
        /**
         * SchedulingDecisionOut
         * @description One scheduling decision: the weights in force and the candidates ranked.
         */
        SchedulingDecisionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Scheduler Name */
            scheduler_name: string;
            /** Alpha */
            alpha: number;
            /** Beta */
            beta: number;
            /** Gamma */
            gamma: number;
            /** Reliability Halflife Seconds */
            reliability_halflife_seconds: number;
            /** Wilson Z */
            wilson_z: number;
            /** Selected Node Id */
            selected_node_id: string | null;
            /** Candidates */
            candidates: components["schemas"]["SchedulingCandidateOut"][];
        };
        /**
         * TelemetrySampleOut
         * @description One recorded telemetry sample, as stored — nulls pass through untouched.
         */
        TelemetrySampleOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Cpu Percent */
            cpu_percent: number;
            /** Ram Used Bytes */
            ram_used_bytes: number;
            /** Ram Total Bytes */
            ram_total_bytes: number;
            /** Gpu */
            gpu: components["schemas"]["GpuTelemetry"][] | null;
            /** Rtt Ms */
            rtt_ms: number | null;
            /** Rtt Ewma Ms */
            rtt_ewma_ms: number | null;
        };
        /**
         * TokenRefreshRequest
         * @description Body of POST /auth/token/refresh.
         *
         *     ``signature`` is the base64-encoded Ed25519 signature over the UTF-8 bytes
         *     of the issued ``nonce`` string.
         */
        TokenRefreshRequest: {
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Nonce */
            nonce: string;
            /** Signature */
            signature: string;
        };
        /**
         * TokenResponse
         * @description A freshly issued node access token.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_enrollment_token_endpoint_auth_enrollment_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentTokenCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTokenCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_challenge_auth_challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_token_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_nodes_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_nodes__node_id__heartbeat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nodes_endpoint_nodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeListResponse"];
                };
            };
        };
    };
    get_node_endpoint_nodes__node_id__get: {
        parameters: {
            query?: {
                /** @description Number of recent telemetry samples to include (capped). */
                samples?: number | null;
            };
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_endpoint_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
        };
    };
    submit_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_endpoint_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_scheduling_decisions_jobs__job_id__scheduling_decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulingDecisionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_endpoint_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_lease_nodes__node_id__leases_claim_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_leases__lease_id__renew_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                lease_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseEpochRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_leases__lease_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                lease_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseEpochRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fail_leases__lease_id__fail_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                lease_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseFailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
